doctrine_migrations:
    # Syntaxe moderne par défaut de Symfony / Doctrine
    migrations_paths:
        'DoctrineMigrations': '%kernel.project_dir%/migrations'

    # Paramètres de stockage de la table de version
    storage:
        table_storage:
            table_name: 'doctrine_migration_versions'

    enable_profiler: '%kernel.debug%'
